<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>okta</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-boot-okta-demo</name>
	<description>Demo project for Spring Boot</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>

	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>

	<properties>
		<java.version>21</java.version>
		<okta.authn.version>3.0.0</okta.authn.version>
<!--		<okta.sdk.version>25.0.0</okta.sdk.version>-->
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.okta.idx.sdk</groupId>
			<artifactId>okta-idx-java-api</artifactId>
			<version>4.0.1</version>
		</dependency>

		<dependency>
			<groupId>com.okta.authn.sdk</groupId>
			<artifactId>okta-authn-sdk-api</artifactId>
			<version>${okta.authn.version}</version>
		</dependency>
		<dependency>
			<groupId>com.okta.authn.sdk</groupId>
			<artifactId>okta-authn-sdk-impl</artifactId>
			<version>${okta.authn.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.okta.commons</groupId>
			<artifactId>okta-http-httpclient</artifactId>
			<version>2.0.2</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>com.okta.sdk</groupId>-->
<!--			<artifactId>okta-sdk-httpclient</artifactId>-->
<!--			<version>${okta.sdk.version}</version>-->
<!--			<scope>runtime</scope>-->
<!--		</dependency>-->
		<dependency>
			<groupId>com.okta.spring</groupId>
			<artifactId>okta-spring-sdk</artifactId>
			<version>3.0.8</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>com.okta.sdk</groupId>-->
<!--			<artifactId>okta-sdk-api</artifactId>-->
<!--			<version>${okta.sdk.version}</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>com.okta.sdk</groupId>-->
<!--			<artifactId>okta-sdk-impl</artifactId>-->
<!--			<version>${okta.sdk.version}</version>-->
<!--			<scope>runtime</scope>-->
<!--		</dependency>-->

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-restclient</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.16.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-restclient-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
